Repository slidewiki/slidewiki-platform, pull requests merged in 2018-12, with the labels that each got.

#990 Lti group
  actions/slide/addLTI.js
  actions/user/userprofile/cancelUserlti.js
  actions/user/userprofile/chooseAction.js
  actions/user/userprofile/deleteUserlti.js
  actions/user/userprofile/leaveUserlti.js
  actions/user/userprofile/saveUserlti.js
  actions/user/userprofile/updateUserlti.js
  components/Deck/ContentPanel/ContentActions/DownloadModal.js
  components/Deck/ContentPanel/SlideModes/SlideEditPanel/SlideContentEditor.js
  components/Deck/SlideEditLeftPanel/SlideEditLeftPanel.js
  components/Login/LTI.js
  components/User/UserProfile/CategoryBox.js
  components/User/UserProfile/ChangePersonalData.js
  components/User/UserProfile/Integrations.js
  components/User/UserProfile/UserLTIEdit.js
  components/User/UserProfile/UserLTIs.js
  components/User/UserProfile/UserProfile.js
  configs/general.js
  configs/microservices.sample.js
  configs/routes.js
  intl/ca.json
  intl/default.json
  intl/el.json
  intl/en.json
  intl/fy.json
  intl/gd.json
  intl/pt.json
  intl/ru.json
  package.json
  server.js
  services/lticonsumer.js
  services/userProfile.js
  services/userlti.js
  stores/SlideEditStore.js
  stores/UserProfileStore.js
Labels: do not merge

#1124 SWIK-906 Robots.txt
  package.json
  robots.txt
  server.js
Labels: enhancement

#1140 Swik 2628 fix conflicting hidden css style
  assets/css/home-custom.css
  components/common/SingleItemAccordion.js
Labels: bugfix
